# Generated by Django 4.1.1 on 2022-09-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('txt1', models.CharField(max_length=10)),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('num3', models.IntegerField()),
            ],
        ),
    ]
