# Generated by Django 4.1.1 on 2022-09-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('download_csv', 'Can download csv of all items')]},
        ),
    ]
